-- SAFE MIGRATION SCRIPT
-- This script handles existing tables/policies gracefully.

-- 1. PROFILES (Ensure exists)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  display_name text,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.profiles enable row level security;

-- Add 'is_public' column safely
alter table public.profiles 
add column if not exists is_public boolean default false;

-- Profile Policies (Drop then Create to avoid errors)
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );


-- 2. REVIEWS
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, service_id)
);
alter table public.reviews enable row level security;

-- Review Policies
drop policy if exists "Reviews are viewable by everyone." on reviews;
create policy "Reviews are viewable by everyone." on reviews for select using ( true );

drop policy if exists "Users can create/update their own reviews." on reviews;
create policy "Users can create/update their own reviews." on reviews for all using ( auth.uid() = user_id );


-- 3. SERVICE VOTES
create table if not exists public.service_votes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  vote_type text check (vote_type in ('favorite', 'wasteful')),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, vote_type)
);
alter table public.service_votes enable row level security;

-- Vote Policies
drop policy if exists "Votes are viewable by everyone." on service_votes;
create policy "Votes are viewable by everyone." on service_votes for select using ( true );

drop policy if exists "Users can manage their own votes." on service_votes;
create policy "Users can manage their own votes." on service_votes for all using ( auth.uid() = user_id );


-- 4. USER SUBSCRIPTIONS (For Cloud Sync / Public Profiles)
create table if not exists public.user_subscriptions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  name_custom text,
  price numeric not null,
  currency text not null,
  cycle text not null,
  category text,
  description text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.user_subscriptions enable row level security;

-- Subscription Policies
drop policy if exists "Users can manage own subscriptions" on user_subscriptions;
create policy "Users can manage own subscriptions" on user_subscriptions for all using ( auth.uid() = user_id );

drop policy if exists "Public view if profile is public" on user_subscriptions;
create policy "Public view if profile is public" on user_subscriptions for select using (
    exists (
      select 1 from profiles
      where profiles.id = user_subscriptions.user_id
      and profiles.is_public = true
    )
);

-- 5. FUNCTION TRIGGER (For New Users)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, split_part(new.email, '@', 1))
  on conflict (id) do nothing; -- Handle potential conflict
  return new;
end;
$$ language plpgsql security definer;

-- Trigger logic (Drop then Create)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
