-- DANGER: DATA RESET SCRIPT
-- This script will DELETE ALL DATA by dropping the tables and recreating them.
-- Use this if you want a completely fresh start.

-- 1. DROP EXISTING TABLES (CASCADE to remove dependent objects like policies)
drop table if exists public.reviews cascade;
drop table if exists public.service_votes cascade;
drop table if exists public.user_subscriptions cascade;
drop table if exists public.profiles cascade;

-- 2. RECREATE EXTENSIONS
create extension if not exists "uuid-ossp";

-- 3. PROFILES
create table public.profiles (
  id uuid references auth.users not null primary key,
  display_name text,
  avatar_url text,
  is_public boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- 4. REVIEWS
create table public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, service_id)
);
alter table public.reviews enable row level security;

create policy "Reviews are viewable by everyone." on reviews for select using ( true );
create policy "Users can create/update their own reviews." on reviews for all using ( auth.uid() = user_id );

-- 5. SERVICE VOTES
create table public.service_votes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  vote_type text check (vote_type in ('favorite', 'wasteful')),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, vote_type)
);
alter table public.service_votes enable row level security;

create policy "Votes are viewable by everyone." on service_votes for select using ( true );
create policy "Users can manage their own votes." on service_votes for all using ( auth.uid() = user_id );

-- 6. USER SUBSCRIPTIONS
create table public.user_subscriptions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  name_custom text,
  price numeric not null,
  currency text not null,
  cycle text not null,
  category text,
  description text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.user_subscriptions enable row level security;

create policy "Users can manage own subscriptions" on user_subscriptions for all using ( auth.uid() = user_id );
create policy "Public view if profile is public" on user_subscriptions for select using (
    exists (
      select 1 from profiles
      where profiles.id = user_subscriptions.user_id
      and profiles.is_public = true
    )
);

-- 7. TRIGGERS
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, split_part(new.email, '@', 1))
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Recreate trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
