-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  display_name text,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- REVIEWS TABLE
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, service_id)
);

alter table public.reviews enable row level security;

create policy "Reviews are viewable by everyone."
  on reviews for select
  using ( true );

create policy "Users can create/update their own reviews."
  on reviews for all
  using ( auth.uid() = user_id );

-- SERVICE VOTES TABLE (For Ranking)
create table if not exists public.service_votes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  service_id text not null,
  vote_type text check (vote_type in ('favorite', 'wasteful')),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, vote_type) -- One favorite and one wasteful vote per user
);

alter table public.service_votes enable row level security;

create policy "Votes are viewable by everyone."
  on service_votes for select
  using ( true );

create policy "Users can manage their own votes."
  on service_votes for all
  using ( auth.uid() = user_id );

-- Function to handle new user signup (auto-create profile)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
